config/routes.rb
Rails.application.routes.draw do
  get 'appointments', to: 'public#all_appointments', as: 'appointments'
  get 'exports', to: 'exports#new', as: 'exports'
  post 'exports', to: 'exports#create', as: 'export_pdf'

  scope "/accounts" do
    resources :users
  end
  devise_for :users

  resources :professionals do
    resources :appointments do
      collection do
        delete 'cancel', to: 'appointments#cancel', as: 'cancel'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "public#home"
end

app/models/professional.rb
class Professional < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :valid_appointments, -> {
                                  where(active: true).where("date > ?", Date.yesterday)
                                }, class_name: 'Appointment'
  validates :name, :title, :surname, presence: true, length: { maximum: 255 }
  validates :active, inclusion: { in: [true, false] }
  before_destroy :can_destroy?, prepend: true
  before_destroy { throw(:abort) if errors.present? }

  scope :active, -> { where(active: true) }

  def to_s
    "#{title} #{name.first}. #{surname}"
  end

  def appointments?
    total > 0
  end

  def cancel_appointments_logical
    appointments.where("date > ?", Date.today.beginning_of_day).each do |a|
      a.soft_delete
    end
  end

  def cancel_appointments_physical
    appointments.destroy_all
  end

  protected

  def can_destroy?
    if appointments?
      errors.add(:base, "This professional cannot be deleted, they still have appointments.")
      throw :abort
    end
  end
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  load_and_authorize_resource
  before_action :load_titles, only: [:new, :edit]

  # GET /professionals
  def index
    @professionals = Professional.all
  end

  # GET /professionals/1
  def show
  end

  # GET /professionals/new
  def new
    @professional = Professional.new
  end

  # GET /professionals/1/edit
  def edit
  end

  # POST /professionals
  def create
    @professional = Professional.new(professional_params)

    if @professional.save
      redirect_to @professional, notice: 'Professional was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /professionals/1
  def update
    if @professional.update(professional_params)
      redirect_to @professional, notice: 'Professional was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /professionals/1
  def destroy
    if @professional.destroy
      redirect_to professionals_url, notice: 'Professional was successfully destroyed.'
    else
      redirect_to professionals_url, alert: @professional.errors.full_messages.join
    end
  end

  private

  def load_titles
    @titles = %w[Dr. Lic. Ing.]
  end

  # Only allow a list of trusted parameters through.
  def professional_params
    params.require(:professional).permit(:title, :name, :surname, :active)
  end
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
  def full_name(professional)
    "#{professional.title} #{professional.name.first} #{professional.surname}"
  end
end

app/views/professionals/_form.html.erb
<%= form_with(model: professional) do |form| %>
  <% if professional.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professional.errors.count, "error") %> prohibited this professional from being saved:</h2>

      <ul>
        <% professional.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-sm-6">
    <div class="field">
      <%= form.label :title %><br />
      <%= form.select :title, @titles.each {|x| [x]}, {}, class: "multiple form-control" %>
    </div>

    <div class="field">
      <%= form.label :name %><br />
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :surname %><br />
      <%= form.text_field :surname, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :active %>
      <%= form.check_box :active %>
    </div>

    <div class="actions">
      <%= form.submit class: "form-control btn btn-primary btn-sm" %>
    </div>
  </div>
</div>
<% end %>

app/views/professionals/edit.html.erb
<h2>Editing Professional</h2>

<%= render 'form', professional: @professional %>

<%= link_to 'Show', @professional, class: "btn btn-primary btn-sm" %> |
<%= link_to 'Back', professionals_path, class: "btn btn-secondary btn-sm" %>

app/views/professionals/index.html.erb
<% content_for :page_title, "Professionals" %>

<h2>Professionals</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th colspan="4">Appointments</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @professionals.each do |professional| %>
      <tr>
        <td><%= professional.to_s%></td>
        <td><%= professional.total%></td>
        <td>
         <% if can? :create, Appointment %>
        <%= link_to 'New', new_professional_appointment_path(professional) %>
        <% end %>
        </td>
        <td><%= link_to 'See All', professional_appointments_path(professional) %></td>
        
        <td>
        <% if can? :destroy, Appointment %>
        <%= link_to 'Cancel All', cancel_professional_appointments_path(professional), method: :delete %>
        <%end%>
        </td>
        
        <td><%= link_to 'Show', professional %></td>
        <% if can? :update, Professional %>
        <td><%= link_to 'Edit', edit_professional_path(professional) %></td>
        <% end %>
        <% if can? :destroy, Professional %>
        <td><%= link_to 'Destroy', professional, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 <% if can? :create, Professional %>
<%= link_to 'New Professional', new_professional_path, class: "btn btn-primary btn-sm" %>
<% end %>

app/views/professionals/new.html.erb
<h2>New Professional</h2>

<%= render 'form', professional: @professional %>

<%= link_to 'Back', professionals_path, class: "btn btn-secondary btn-sm" %>

app/views/professionals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @professional.title %>
</p>

<p>
  <strong>Name:</strong>
  <%= @professional.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @professional.surname %>
</p>

<p>
  <strong>Appointments:</strong>
  <%= link_to 'Appointments', professional_appointments_path(@professional) %>
</p>

<p>
  <strong>Active:</strong>
  <%= @professional.active %>
</p>



<% if can? :update, Professional %>
<%= link_to 'Edit', edit_professional_path(@professional), class: "btn btn-primary btn-sm" %> |
<% end %>
<%= link_to 'Back', professionals_path, class: "btn btn-secondary btn-sm" %>