config/routes.rb
Rails.application.routes.draw do
  get 'appointments', to: 'public#all_appointments', as: 'appointments'
  get 'exports', to: 'exports#new', as: 'exports'
  post 'exports', to: 'exports#create', as: 'export_pdf'

  scope "/accounts" do
    resources :users
  end
  devise_for :users

  resources :professionals do
    resources :appointments do
      collection do
        delete 'cancel', to: 'appointments#cancel', as: 'cancel'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "public#home"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :trackable, :rememberable, :validatable

  validates :role, presence: true
  validates :username, presence: true, uniqueness: true

  enum role: [:user, :manager, :admin]
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:role, :username, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-sm-6">
    <div class="field">
      <%= form.label :username %><br />
      <%= form.text_field :username,autofocus: true, autocomplete: "username", class: "form-control"  %>
    </div>

    <div class="field">
      <%= form.label :role %><br />
      <%= form.select :role, User.roles.keys {|x| [x]}, {}, class: "multiple", class: "form-control"  %>
    </div>

    <div class="field">
      <%= form.label :email %><br />
      <%= form.email_field :email, autocomplete: "email", class: "form-control"  %>
    </div>

    <% if request.path == new_user_path %>
    <div class="field">
      <%= form.label :password %><br />
      <%= form.password_field :password, autocomplete: "password", class: "form-control"  %>
    </div>

    <div class="field">
      <%= form.label :password_confirmation %><br />
      <%= form.password_field :password_confirmation, autocomplete: "password", class: "form-control" %>
    </div>
    <% end %>

    <div class="actions">
      <%= form.submit class: "form-control btn btn-primary btn-sm" %>
    </div>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<h2>Editing User</h2>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user, class: "btn btn-secondary btn-sm" %> |
<%= link_to 'Back', users_path, class: "btn btn-secondary btn-sm" %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Username</th>
      <th scope="col">Email</th>
      <th scope="col">Role</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: "btn btn-primary btn-sm" %>

app/views/users/new.html.erb
<h2>New User</h2>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path, class: "btn btn-secondary btn-sm" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%=  @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <%=  @user.role %>
</p>


<%= link_to 'Edit', edit_user_path(@user), class: "btn btn-primary btn-sm" %> |
<%= link_to 'Back', users_path, class: "btn btn-primary btn-sm" %>