config/routes.rb
Rails.application.routes.draw do
  get 'appointments', to: 'public#all_appointments', as: 'appointments'
  get 'exports', to: 'exports#new', as: 'exports'
  post 'exports', to: 'exports#create', as: 'export_pdf'

  scope "/accounts" do
    resources :users
  end
  devise_for :users

  resources :professionals do
    resources :appointments do
      collection do
        delete 'cancel', to: 'appointments#cancel', as: 'cancel'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "public#home"
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :professional, -> { where active: true }, counter_cache: :total
  validates :name, :phone, :surname, presence: true, length: { maximum: 255 }
  validates :date, timeliness: { on_or_after: lambda { Date.current }, type: :datetime },
                   uniqueness: { scope: :professional_id }
  validates :active, inclusion: { in: [true, false] }
  validate :date, :not_weekend, on: :create
  validates_time :time, :on_or_after => '8:00am',
                        :on_or_after_message => 'Appointments only during working hours (08:00-17:00hs)',
                        :before => '17:00pm',
                        :allow_nil => false

  scope :active, -> { where(active: true) }
  scope :order_by_latest_first, -> { order(date: :asc) }
  scope :all_valid_appointments, -> { where(active: true).where("date > ?", Date.yesterday) }


  def valid_and_future
    active && date > Date.yesterday
  end

  def appointee
    "#{name} #{surname}"
  end

  def soft_delete
    active = false
  end


  #  use cron jobs to clear old appointments
  def logical_past_date
    if date > Date.yesterday
      active = false
    end
  end

  def physical_past_date
    if date > Date.yesterday
      destroy
    end
  end

  def not_weekend
    if date.saturday? || date.sunday?
      errors.add(:date, 'No appointments on weekends.')
    end
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  load_and_authorize_resource :professional
  load_and_authorize_resource :appointment, through: :professional

  # GET /appointments
  def index
    @appointments = @professional.valid_appointments.order_by_latest_first.order(:date)
  end

  # GET /appointments/1
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  def create
    @appointment = @professional.appointments.new(appointment_params)

    if @appointment.save
      redirect_to [@professional, @appointment], notice: 'Appointment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /appointments/1
  def update
    if @appointment.update(appointment_params)
      redirect_to [@professional, @appointment], notice: 'Appointment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /appointments/1
  def destroy
    @appointment.destroy
    redirect_to professional_appointments_url, notice: 'Appointment was successfully destroyed.'
  end

  def cancel
    @professional.cancel_appointments_physical
    redirect_to professionals_url, notice: 'All appointments were successfully destroyed.'
  end

  private

  # Only allow a list of trusted parameters through.
  def appointment_params
    params.require(:appointment).permit(:name, :surname, :phone, :notes, :date, :time, :active)
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
  def display_date(appointment)
    "#{I18n.l(appointment.date, format: '%A, %B %d, %Y')} #{I18n.l(appointment.time, format: 'at %H:%M')}"
  end
end

app/views/appointments/_form.html.erb
<%= form_with(model: [@professional, appointment]) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%#   <div class="field">
    <%= form.label :professional_id %>
    <%# <%= form.select :professional_id, Professional.all {|x| ["#{x.title} #{x.surname}", x.id]}, {}, class: "multiple" %>
  <%# </div> 
  %>
<div class="row">
  <div class="col-sm-6">
    <div class="field">
      <%= form.label :name %><br />
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :surname %><br />
      <%= form.text_field :surname, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :phone %><br />
      <%= form.text_field :phone, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :notes %><br />
      <%= form.text_area :notes, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :active %>
      <%= form.check_box :active %>
    </div>

    <div class="form-group">
      <%= form.label :date %><br />
      <%= form.date_select :date, selected: Date.today, order: [:day, :month, :year], class: "form-control"%>
    </div>

    <div class="form-group">
      <%= form.label :time %><br />
      <%= form.time_select :time, {minute_step: 30} %>
    </div>
    <div class="actions form-group">
      <%= form.submit class: "form-control btn btn-primary btn-sm" %>
    </div>
  </div>
</div>
<% end %>

app/views/appointments/edit.html.erb
<h2>Editing Appointment</h2>

<%= render 'form', professional: @professional, appointment: @appointment %>

<%= link_to 'Show', [@professional, @appointment], class: "btn btn-primary btn-sm" %> |
<%= link_to 'Back', professional_appointments_path(@professional), class: "btn btn-secondary btn-sm" %>

app/views/appointments/index.html.erb
<% content_for :page_title, "Appointments" %>

<h2>Appointments for <%= @professional.to_s %></h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Notes</th>
      <th scope="col">Date</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.order_by_latest_first.each do |appointment| %>
      <tr>
        <td><%= appointment.appointee %></td>
        <td><%= appointment.phone %></td>
        <td><%= appointment.notes %></td>
        <td><%= display_date(appointment) %></td>
        <td><%= link_to 'Show', [@professional, appointment] %></td>
        <% if can? :update, Appointment %>
        <td><%= link_to 'Edit',  edit_professional_appointment_path(@professional, appointment) %></td>
        <% end %>
        <% if can? :destroy, Appointment %>
        <td><%= link_to 'Destroy', [@professional, appointment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', professionals_path, class: "btn btn-secondary btn-sm" %>
<% if can? :create, Appointment %>
<%= link_to 'New Appointment', new_professional_appointment_path(@professional), class: "btn btn-primary btn-sm" %>
<% end %>

app/views/appointments/new.html.erb
<h2>New Appointment for  <%= @professional.to_s %></h2>

<%= render 'form', professional: @professional, appointment: @appointment %>

<%= link_to 'Back', professional_appointments_path(@professional), class: "btn btn-secondary btn-sm" %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Professional:</strong>
  <%=@professional.to_s %>
</p>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @appointment.surname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @appointment.phone %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @appointment.notes %>
</p>

<p>
  <strong>Date:</strong>
  <%= display_date(@appointment) %> 
</p>

<p>
  <strong>Active:</strong>
  <%= @appointment.active %>
</p>
<% if can? :update, Appointment %>
<%= link_to 'Edit', edit_professional_appointment_path(@professional, @appointment), class: "btn btn-primary btn-sm" %> |
<% end %>
<%= link_to 'Back', :back, class: "btn btn-secondary btn-sm" %>