config/routes.rb
Rails.application.routes.draw do
  get 'appointments', to: 'public#all_appointments', as: 'appointments'
  get 'exports', to: 'exports#new', as: 'exports'
  post 'exports', to: 'exports#create', as: 'export_pdf'

  scope "/accounts" do
    resources :users
  end
  devise_for :users

  resources :professionals do
    resources :appointments do
      collection do
        delete 'cancel', to: 'appointments#cancel', as: 'cancel'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "public#home"
end

app/views/layouts/_footer.html.erb
<div class="container bg-white">
    <div class="row">
        <div class="col" id="footer">
            <p>Copyright &copy; <%= Date.current.strftime('%Y')%> Polycon</p>
        </div>
    </div>
</div>

app/views/layouts/_menu.html.erb
<h1 class="float-start" id="site-name">Polycon</h1>

<ul class="float-end list-unstyled" id="topnav">
    <% if user_signed_in? %>
        <li> <%= link_to "Home", root_path %> </li>
        <% if can? :read, User %>
            <li><%= link_to "Users", users_path %> </li>
        <% end %>
        <li><%= link_to "Professionals", professionals_path %> </li>
        <li><%= link_to "All Appointments", appointments_path %> </li>
        <li><%= link_to "Exports", exports_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "#{yield(:page_title)} |" if content_for?(:page_title) %> Polycon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
  </head>

  <body>

    <div class="container bg-white">
      <div class="row">
        <div class="col page-nav">
          <nav>
            <%= render partial: 'layouts/menu' %>
          </nav>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <%= flash_messages %>
          <%= yield %>        
        </div>
      </div>
    </div>

    <%= render partial: 'layouts/footer' %>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

  </body>
</html>